<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use common\models\User;
use common\helpers\CssHelper;
use common\helpers\ConstHelper;

/* @var $this yii\web\View */
/* @var $model common\models\NoteProgress */

$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Progresses Notes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="note-progress-view box box-primary">
    <div class="box-header">
        <p class="text-right">
            <?= Html::a(Yii::t('app', 'Back'), ['index'], ['class' => 'btn btn-warning btn-flat']) ?>
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary btn-flat']) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger btn-flat hidden',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    </div>
    <div class="box-body table-responsive no-padding">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                //'id',
                //'order_id',
                //'visit_id',
                //'provider_id',
                [
                    'attribute' => 'status',
                    'value' => function($model){
                        return ConstHelper::getNoteStatusList($model->status);
                    },
                    'contentOptions' => ['class' => CssHelper::orderStatusCss($model->status)],
                ],
                'patient_name',
                'mrn',
                'dob:date',
                [
                    'attribute' => 'gender',
                    'value' => function($model){
                        return User::getGenderList($model->gender);
                    },
                ],
                'diagnosis',
                'service_provided_pt_evaluation',
                'service_provided_therapeutic_exercises',
                'service_provided_therapeutic_activities',
                'service_provided_bed_mobility',
                'service_provided_gait_training',
                'service_provided_muscle_reduction',
                'service_provided_prosthetic_training',
                'service_provided_home_exercise_program',
                'service_provided_ultrasound',
                'service_provided_hot_pack',
                'service_provided_cold_pack_message',
                'service_provided_massage_mobilization',
                'service_provided_joint_mobilization',
                'service_provided_pt_cg_education',
                'service_provided_other',
                'vital_signs_bp',
                'vital_signs_pulse',
                'vital_signs_resp',
                'vital_signs_spo2',
                'vital_signs_temp',
                'subjective_co',
                'subjective_pain',
                'subjective_fatigue',
                'subjective_weakness',
                'subjective_unsteady_gait',
                'subjective_condition_improved',
                'subjective_pain_intensity',
                'subjective_pain_location',
                'subjective_pain_description',
                'subjective_pain_frequency_all_time',
                'subjective_pain_frequency_daily',
                'subjective_pain_frequency_less_daily',
                'subjective_pain_no_pain',
                'subjective_pain_other',
                'bed_mobility_roll_unable',
                'bed_mobility_roll_max',
                'bed_mobility_roll_mod',
                'bed_mobility_roll_min',
                'bed_mobility_roll_cg',
                'bed_mobility_roll_sba',
                'bed_mobility_roll_s',
                'bed_mobility_roll_i',
                'bed_mobility_bridge_unable',
                'bed_mobility_bridge_max',
                'bed_mobility_bridge_mod',
                'bed_mobility_bridge_min',
                'bed_mobility_bridge_cg',
                'bed_mobility_bridge_sba',
                'bed_mobility_bridge_s',
                'bed_mobility_bridge_i',
                'bed_mobility_supine2sit_unable',
                'bed_mobility_supine2sit_max',
                'bed_mobility_supine2sit_mod',
                'bed_mobility_supine2sit_min',
                'bed_mobility_supine2sit_cg',
                'bed_mobility_supine2sit_sba',
                'bed_mobility_supine2sit_s',
                'bed_mobility_supine2sit_i',
                'bed_mobility_sit2supine_unable',
                'bed_mobility_sit2supine_max',
                'bed_mobility_sit2supine_mod',
                'bed_mobility_sit2supine_min',
                'bed_mobility_sit2supine_cg',
                'bed_mobility_sit2supine_sba',
                'bed_mobility_sit2supine_s',
                'bed_mobility_sit2supine_i',
                'transfer_sit2stand_unable',
                'transfer_sit2stand_max',
                'transfer_sit2stand_mod',
                'transfer_sit2stand_min',
                'transfer_sit2stand_cg',
                'transfer_sit2stand_sba',
                'transfer_sit2stand_s',
                'transfer_sit2stand_i',
                'transfer_bed2chair_unable',
                'transfer_bed2chair_max',
                'transfer_bed2chair_mod',
                'transfer_bed2chair_min',
                'transfer_bed2chair_cg',
                'transfer_bed2chair_sba',
                'transfer_bed2chair_s',
                'transfer_bed2chair_i',
                'transfer_toilet_unable',
                'transfer_toilet_max',
                'transfer_toilet_mod',
                'transfer_toilet_min',
                'transfer_toilet_cg',
                'transfer_toilet_sba',
                'transfer_toilet_s',
                'transfer_toilet_i',
                'transfer_shower_unable',
                'transfer_shower_max',
                'transfer_shower_mod',
                'transfer_shower_min',
                'transfer_shower_cg',
                'transfer_shower_sba',
                'transfer_shower_s',
                'transfer_shower_i',
                'gait_even_surface_distance',
                'gait_even_surface_unable',
                'gait_even_surface_max',
                'gait_even_surface_mod',
                'gait_even_surface_min',
                'gait_even_surface_cg',
                'gait_even_surface_sba',
                'gait_even_surface_s',
                'gait_even_surface_i',
                'gait_uneven_surface_distance',
                'gait_uneven_surface_unable',
                'gait_uneven_surface_max',
                'gait_uneven_surface_mod',
                'gait_uneven_surface_min',
                'gait_uneven_surface_cg',
                'gait_uneven_surface_sba',
                'gait_uneven_surface_s',
                'gait_uneven_surface_i',
                'gait_device',
                'stairs_unable',
                'stairs_max',
                'stairs_mod',
                'stairs_min',
                'stairs_cg',
                'stairs_sba',
                'stairs_s',
                'stairs_i',
                'stairs_steps',
                'stairs_device',
                'pattern',
                'precautions',
                'balance_sitting_static_poor',
                'balance_sitting_static_fair',
                'balance_sitting_static_good',
                'balance_sitting_dynamic_poor',
                'balance_sitting_dynamic_fair',
                'balance_sitting_dynamic_good',
                'balance_standing_static_poor',
                'balance_standing_static_fair',
                'balance_standing_static_good',
                'balance_standing_dynamic_poor',
                'balance_standing_dynamic_fair',
                'balance_standing_dynamic_good',
                'therapeutic_exercises',
                'patient_is_uncooperative',
                'patient_requires_encouragement',
                'patient_is_cooperative',
                'patient_response_today_poor',
                'patient_response_today_fair',
                'patient_response_today_good',
                'patient_response_today_excellent',
                'patient_progress_toward_goals_poor',
                'patient_progress_toward_goals_fair',
                'patient_progress_toward_goals_good',
                'patient_progress_toward_goals_excellent',
                'patient_activity_tolerance_poor',
                'patient_activity_tolerance_fair',
                'patient_activity_tolerance_good',
                'patient_activity_tolerance_excellent',
                'patient_safety_mechanics_poor',
                'patient_safety_mechanics_fair',
                'patient_safety_mechanics_good',
                'patient_safety_mechanics_excellent',
                'assessment_comments',
                'rom_ue',
                'rom_le',
                'rom_cervical',
                'rom_trunk',
                'rom_other',
                'strength_ue',
                'strength_le',
                'strength_cervical',
                'strength_trunk',
                'strength_other',
                'inadequate_safety_awareness',
                'unable_ambulating_outdoors',
                'difficulty_transfer',
                'localized_weakness',
                'inefficient_gait',
                'bed_chair_bound',
                'impaired_balance',
                'requires_assistance_to_leave_home',
                'profound_general_weakness',
                'limited_rom',
                'difficulty_manage_stairs',
                'significant_effort_performing_tasks',
                'pt_plan_comments',
                'therapist_name',
                'therapist_title',
                //'therapist_signature',
                'therapist_name0',
                'therapist_title0',
                //'therapist_signature0',
                'note_date:date',
                'time_in:time',
                'time_out:time',
                [
                    'attribute' => 'created_by',
                    'type' => 'raw',
                    'value' => isset($model->createdBy) ? $model->createdBy->getUserFullName(true) : null
                ],
                'created_at:dateTime',
                [
                    'attribute' => 'updated_by',
                    'type' => 'raw',
                    'value' => isset($model->updatedBy) ? $model->updatedBy->getUserFullName(true) : null
                ],
                'updated_at:dateTime',
            ],
        ]) ?>
    </div>
</div>
