<?php

namespace tests\codeception\frontend\unit\models\forms;

use Yii;
use Codeception\Specify;
use frontend\models\forms\ContactForm;
use tests\codeception\frontend\unit\TestCase;
use yii\base\InvalidConfigException;

/**
 * Class ContactFormTest
 * @package tests\codeception\frontend\unit\models\forms
 * @group contact_form
 */
class ContactFormTest extends TestCase
{
    use Specify;

    protected function _setUp()
    {
        return parent::_setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Create the objects against which you will test.
     * @throws InvalidConfigException
     */
    protected function setUp() : void
    {
        parent::setUp();
        Yii::$app->mailer->fileTransportCallback = function ($mailer, $message) {
            return 'testing_message_contact.eml';
        };
    }

    /**
     * Clean up the objects against which you tested.
     */
    protected function tearDown() :void
    {
        if(is_file($this->_getMessageFile())){
            unlink($this->_getMessageFile());
        }
        parent::tearDown();
    }

    /**
     * Test contact.
     */
    public function testContact()
    {
        $model = new ContactForm();

        $model->attributes = [
            'name' => 'Tester',
            'email' => 'tester@example.com',
            'subject' => 'very important letter subject',
            'body' => 'body of current message',
        ];

        $model->sendContactEmail('admin@example.com');

        $this->specify('email should be send', function () {
            expect('email file should exist', file_exists($this->_getMessageFile()))->true();
        });

        $this->specify('message should contain correct data', function () use ($model) {
            $emailMessage = file_get_contents($this->_getMessageFile());

            expect('email should contain user name', $emailMessage)->stringContainsString($model->name);
            expect('email should contain sender email', $emailMessage)->stringContainsString($model->email);
            expect('email should contain subject', $emailMessage)->stringContainsString($model->subject);
            expect('email should contain body', $emailMessage)->stringContainsString($model->body);
        });
    }

    /**
     * Get message file that our test will create to put contact data in
     * (we are simulating email sending in our test by writing data to file).
     *
     * @return string
     */
    private function _getMessageFile()
    {
        return Yii::getAlias(Yii::$app->mailer->fileTransportPath) . '/testing_message_contact.eml';
    }
}